### ISSUE TITLE
The specified bucket does not exist in Step 3: Upload app code to an Amazon S3 bucket

### ISSUE THREAD

**Issue by libert-xyz** [awsdocs/aws-opsworks-user-guide#16]
The object **opsworks-nodejs-demo-app.zip** doesn't exist in the **Step 3: Upload app code to an Amazon S3 bucket**

Object Links: https://s3.amazonaws.com/opsworks-codepipeline-demo/opsworks-nodejs-demo-app.zip

**Comment by GitGaby** [comment]
Thanks, Libert. I have updated the link to the Node.js demo app.
